### ISSUE TITLE
掛け率、単価について

### ISSUE THREAD

**Issue by metyarin** [x-point-1/cestlavie-app2#13]
デフォルトは空に
掛け率、単価を登録しない時もある

クライアントマスタと品番より、掛け率、単価は取得で
掛け率と単価は表示

**Comment by metyarin** [comment]
単価は棚卸し用CSVアップロードのときに取り込めるようにしてそれを使ってください

**Comment by metyarin** [comment]
掛け率はclient->joudai_percentです

**Comment by tatsuya-o** [comment]
@metyarin 
> 単価は棚卸し用CSVアップロード
手持ちのcsvにヘッダ行が見当たらなかったので，何列目が単価なのか教えてください
