### ISSUE TITLE
既存レコード読み込み

### ISSUE THREAD

**Issue by metyarin** [x-point-1/cestlavie-app2#2]
これレコード番号じゃなくって、レコード名ですね
レコード番号知る方法が無い気がする

**Comment by tatsuya-o** [comment]
@metyarin 
レコード名は同一モードでしか重複許可しないというのは可能ですが，完全に一意ではないので今の構造だとそれは実現できないと思うのですがどうでしょう

**Comment by metyarin** [comment]
@tatsuya-o 完全に一意ではないのはなんで？

**Comment by tatsuya-o** [comment]
@metyarin 
単に同じモード内で同じ名前のレコードが複数存在するという意味です
例えば，
[{id: 1, name: 'hoge', 'mode': 1},
{id: 2, name: 'hoge',  'mode': 2}]
が存在する時に，
レコード名の検索で'hoge'を入力した場合，どちらのレコードの情報を読み取りページに渡すのか決まらないということです

**Comment by metyarin** [comment]
@tatsuya-o 違うモードで別の名前は作れないようにしてください

**Comment by tatsuya-o** [comment]
@metyarin 同じモードの話です．どちらにしろ，この場合はモードを抜きにしても話は変わりません．
